import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Upload, AlertCircle, Check, FileJson } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { paymentRowLabel } from "@/tax/taxLabels";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/layout/PageHeader";
import { isTauri } from "@/lib/environment";
import { useSettingsStore } from "@/stores/settings.store";
import { formatMoney } from "@/lib/format";
import { parseItrJson, type ParseResult } from "@/tax/itrParser";
import {
  clearRowsBySourcePrefix, insertDeduction, insertIncome, insertPayment,
  upsertAssessment, upsertTaxYear,
} from "@/db/tax";
import { useQueuedDocumentImport } from "@/hooks/useQueuedDocumentImport";

const DEFAULT_AY = "2026-27";

type Stage = "idle" | "review" | "done";

export function TaxImportPage() {
  const navigate = useNavigate();
  const currency = useSettingsStore((s) => s.settings.currency);
  const [stage, setStage] = useState<Stage>("idle");
  const [parsed, setParsed] = useState<ParseResult | null>(null);
  const [filename, setFilename] = useState<string>("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const queue = useQueuedDocumentImport("itr_json");

  const importFile = async (f: File): Promise<void> => {
    setBusy(true);
    setError(null);
    try {
      const text = await f.text();
      const json = JSON.parse(text);
      const r = parseItrJson(json, f.name);
      if (!r.itrForm) {
        setError("This file doesn't look like an ITR JSON for AY 2026-27 (no ITR1/ITR2/ITR3/ITR4 root found).");
        return;
      }
      setParsed(r);
      setFilename(f.name);
      setStage("review");
    } catch (err) {
      setError(err instanceof Error ? `Could not parse JSON: ${err.message}` : String(err));
    } finally {
      setBusy(false);
    }
  };

  const handleFile: React.ChangeEventHandler<HTMLInputElement> = (e) => {
    const f = e.target.files?.[0];
    if (f) void importFile(f);
  };

  // Bulk-folder-import hand-off. This page has no AY field of its own (AY is
  // derived from the parsed document itself), so there's no equivalent of
  // the other pages' "prefill ay from queue.pendingAy" step.
  useEffect(() => {
    if (queue.pendingFile) void importFile(queue.pendingFile);
    // `importFile` intentionally excluded from deps — see Form16ImportPage's
    // identical comment; only `queue.pendingFile` should retrigger this.
  }, [queue.pendingFile]);

  const commit = async () => {
    if (!parsed?.itrForm) return;
    setBusy(true);
    setError(null);
    try {
      const ay = parsed.ay ?? "2026-27";
      await upsertTaxYear(ay, {
        itr_form: parsed.itrForm,
        itr_form_source: "import",
        imported_filename: filename,
      });
      // itrParser source paths all start with "ITR." — clear only those so a
      // prior AIS import (source_path "AIS:…") isn't wiped out.
      await clearRowsBySourcePrefix(ay, "ITR.");
      for (const r of parsed.income) await insertIncome({ ...r, ay, note: null, excluded: false });
      for (const r of parsed.deductions) await insertDeduction({ ...r, ay, note: null });
      for (const r of parsed.payments) await insertPayment({ ...r, ay, note: null });
      await upsertAssessment({ ay, ...parsed.assessment });
      setStage("done");
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  };

  if (!isTauri()) {
    return (
      <div className="container max-w-2xl py-6">
        <PageHeader backTo="/tax" backLabel="Back to tax" title="Import ITR JSON" />
        <Card className="mt-4 border-amber-300/60 bg-amber-50/40 dark:bg-amber-950/20">
          <CardContent className="py-3 text-xs text-amber-900 dark:text-amber-200">
            Run in the desktop app to import.
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="container max-w-3xl py-6">
      <PageHeader
        backTo="/tax"
        backLabel="Back to tax"
        title="Import ITR JSON"
        description="Paste in a JSON file generated by the offline utility or downloaded as a prefilled return. Schema follows the AY 2026-27 ITR-1 / 2 / 4 spec; older schemas may import partially."
      />

      {error && (
        <Card className="mb-4 border-destructive/60">
          <CardContent className="py-3 text-xs text-destructive">{error}</CardContent>
        </Card>
      )}

      {stage === "idle" && (
        <Card>
          <CardContent className="flex flex-col items-center gap-4 py-12 text-center">
            <Upload className="h-10 w-10 text-muted-foreground" />
            <p className="text-sm font-medium">Pick an ITR .json file</p>
            <Label
              htmlFor="itrfile"
              data-testid="tax-import-dropzone"
              className="cursor-pointer rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
            >
              {busy ? "Reading…" : "Choose file"}
              <input
                id="itrfile"
                data-testid="tax-import-input"
                type="file"
                accept=".json,application/json"
                className="hidden"
                onChange={handleFile}
                disabled={busy}
              />
            </Label>
          </CardContent>
        </Card>
      )}

      {stage === "review" && parsed && (
        <ReviewSection parsed={parsed} filename={filename} currency={currency} busy={busy} onCommit={commit} onBack={() => { setStage("idle"); setParsed(null); }} />
      )}

      {stage === "done" && parsed && (
        <Card>
          <CardContent className="space-y-3 py-6">
            <div className="flex items-center gap-2">
              <div className="rounded-full bg-emerald-100 p-1 dark:bg-emerald-950">
                <Check className="h-4 w-4 text-emerald-700 dark:text-emerald-400" />
              </div>
              <h3 data-testid="tax-done" className="text-base font-semibold">Imported AY {parsed.ay ?? "2026-27"} as ITR-{parsed.itrForm}</h3>
            </div>
            <ul className="text-sm text-muted-foreground">
              <li>{parsed.income.length} income line(s)</li>
              <li>{parsed.deductions.length} deduction(s)</li>
              <li>{parsed.payments.length} tax payment(s)</li>
              {parsed.unmappedKeyCount > 0 && (
                <li className="text-amber-700 dark:text-amber-300">
                  {parsed.unmappedKeyCount} top-level section(s) in the file weren&apos;t mapped — they&apos;re harmless but if a figure is missing on the detail page that&apos;s likely why.
                </li>
              )}
            </ul>
            {queue.hasNext ? (
              <div className="flex gap-2 pt-2">
                <Button onClick={() => queue.goToNextInQueue(parsed.ay ?? DEFAULT_AY)}>
                  Next file ({(queue.queuePosition ?? 0) + 1} of {queue.queueTotal})
                </Button>
              </div>
            ) : (
              <>
                {queue.queueTotal && queue.queueTotal > 1 && (
                  <p className="text-xs text-muted-foreground">Last of {queue.queueTotal} documents from your folder import.</p>
                )}
                <div className="flex gap-2 pt-2">
                  <Button onClick={() => navigate(`/tax/${encodeURIComponent(parsed.ay ?? DEFAULT_AY)}`)}>
                    Open AY {parsed.ay ?? DEFAULT_AY}
                  </Button>
                  <Button variant="ghost" onClick={() => { setStage("idle"); setParsed(null); }}>
                    Import another
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function ReviewSection({
  parsed, filename, currency, busy, onCommit, onBack,
}: {
  parsed: ParseResult;
  filename: string;
  currency: string;
  busy: boolean;
  onCommit: () => void;
  onBack: () => void;
}) {
  return (
    <div className="space-y-4">
      <Card>
        <CardContent className="flex flex-wrap items-center gap-3 py-3 text-sm">
          <FileJson className="h-4 w-4 text-muted-foreground" />
          <span className="font-medium">{filename}</span>
          <span className="text-muted-foreground">·</span>
          <span>AY <strong>{parsed.ay ?? "(unknown)"}</strong></span>
          <span className="text-muted-foreground">·</span>
          <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs text-primary">ITR-{parsed.itrForm}</span>
          {(parsed.unmappedKeyCount > 0 || parsed.unnamedPayerCount > 0) && (
            <span className="ml-auto flex items-center gap-2">
              {parsed.unmappedKeyCount > 0 && (
                <span data-testid="tax-unmapped" className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-900 dark:bg-amber-950 dark:text-amber-100">
                  <AlertCircle className="h-3 w-3" /> {parsed.unmappedKeyCount} unmapped section(s)
                </span>
              )}
              {parsed.unnamedPayerCount > 0 && (
                <span className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-900 dark:bg-amber-950 dark:text-amber-100">
                  <AlertCircle className="h-3 w-3" /> {parsed.unnamedPayerCount} unnamed payer(s)
                </span>
              )}
            </span>
          )}
        </CardContent>
      </Card>

      <Section title={`Income (${parsed.income.length})`}>
        {parsed.income.length === 0 ? (
          <p className="px-4 py-3 text-xs text-muted-foreground">None extracted.</p>
        ) : (
          <PreviewTable rows={parsed.income.map((r) => ({ a: r.label, b: r.head, c: r.amount }))} currency={currency} />
        )}
      </Section>

      <Section title={`Deductions (${parsed.deductions.length})`}>
        {parsed.deductions.length === 0 ? (
          <p className="px-4 py-3 text-xs text-muted-foreground">None extracted.</p>
        ) : (
          <PreviewTable rows={parsed.deductions.map((r) => ({ a: r.label, b: r.section, c: r.amount }))} currency={currency} />
        )}
      </Section>

      <Section title={`Tax payments (${parsed.payments.length})`}>
        {parsed.payments.length === 0 ? (
          <p className="px-4 py-3 text-xs text-muted-foreground">None extracted.</p>
        ) : (
          <PreviewTable rows={parsed.payments.map((r) => ({ a: paymentRowLabel(r).label, b: r.type, c: r.amount }))} currency={currency} />
        )}
      </Section>

      <Card>
        <CardContent className="grid grid-cols-2 gap-x-4 gap-y-1 py-3 text-sm sm:grid-cols-4">
          <Stat label="Gross total" v={parsed.assessment.gross_total_income} currency={currency} />
          <Stat label="Total income" v={parsed.assessment.total_income} currency={currency} />
          <Stat label="Net tax" v={parsed.assessment.net_tax_liability} currency={currency} />
          <Stat label="Refund / due" v={parsed.assessment.refund_or_balance} currency={currency} />
        </CardContent>
      </Card>

      <div className="flex justify-between">
        <Button variant="ghost" onClick={onBack} disabled={busy}>Back</Button>
        <Button data-testid="tax-commit" onClick={onCommit} disabled={busy}>
          {busy ? "Saving…" : "Save to database"}
        </Button>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card>
      <CardContent className="p-0">
        <div className="border-b px-4 py-2 text-sm font-medium">{title}</div>
        {children}
      </CardContent>
    </Card>
  );
}

function PreviewTable({ rows, currency }: { rows: { a: string; b: string; c: number }[]; currency: string }) {
  return (
    <table className="w-full text-sm">
      <tbody>
        {rows.map((r, i) => (
          <tr key={i} className="border-t first:border-t-0">
            <td className="px-4 py-1.5">{r.a}</td>
            <td className="px-4 py-1.5 text-xs text-muted-foreground">{r.b}</td>
            <td className="px-4 py-1.5 text-right tabular-nums">{formatMoney(r.c, currency)}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function Stat({ label, v, currency }: { label: string; v: number | null; currency: string }) {
  return (
    <div>
      <p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p>
      <p className="font-medium tabular-nums">{v != null ? formatMoney(v, currency) : "—"}</p>
    </div>
  );
}
